# Generated by Django 5.2.6 on 2025-10-23 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('comedy', 'Comedy'), ('action', 'Action'), ('drama', 'Drama')])),
                ('thumbnail_url', models.FileField(upload_to='thumbnails/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(null=True, upload_to='videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'mkv', 'webm', 'avi'])])),
                ('hls_480p', models.FileField(blank=True, editable=False, null=True, upload_to='hls/')),
                ('hls_720p', models.FileField(blank=True, editable=False, null=True, upload_to='hls/')),
                ('hls_1080p', models.FileField(blank=True, editable=False, null=True, upload_to='hls/')),
            ],
        ),
    ]
